### ISSUE TITLE
Логинная зона. Нет сообщения об отправке email

### ISSUE THREAD

**Issue by Nenuahule** [aikus/sql-exam#106]
При восстановлении пароля нет сообщения о том, что пароль отправлен, хотя с бека приходит.

![image](https://user-images.githubusercontent.com/103943533/198981613-714509d8-ada5-43c7-af02-d9b8cf068e24.png)

**Comment by germanovn** [comment]
Странное сообщение:
Для восстановления пароля необходимо разлогиниться
