### ISSUE TITLE
Бесконечный лоадер при удалении курса

### ISSUE THREAD

**Issue by Nenuahule** [aikus/sql-exam#107]
![image](https://user-images.githubusercontent.com/103943533/198984346-bb9724a3-bbff-4eef-bc67-5bb19994292c.png)

![image](https://user-images.githubusercontent.com/103943533/198985397-762c93f2-1358-4713-b9fe-831b0fddef14.png)

**Comment by germanovn** [comment]
Требуется выводить ошибки в портал

**Comment by germanovn** [comment]
На уровне бизнеса решили, что необходимо сделать флаг удаления, и не удалять саму запись
