### ISSUE TITLE
Бесконечный лоадер на удалении шага курса

### ISSUE THREAD

**Issue by Nenuahule** [aikus/sql-exam#112]
![image](https://user-images.githubusercontent.com/103943533/199169491-30e14673-314e-40c2-8b73-211e9b663d3f.png)

**Comment by germanovn** [comment]
Требуется выводить ошибки в портал

**Comment by germanovn** [comment]
На уровне бизнеса решили, что необходимо сделать флаг удаления, и не удалять саму запись
