### ISSUE TITLE
Блок прохождения курса (результаты)

### ISSUE THREAD

**Issue by Slumzur** [aikus/sql-exam#117]
По завершению прохождения перенаправлять на страницу с результатами прохождения. 

В виджете с завершёнными курсами делаем кнопку "посмотреть результаты". Она ссылается на страницу результатов.

В результатах выводим таблицу с полями: название курса, правильный либо последний не пустой ответ студента, иконку (правильно, не правильно)

**Comment by germanovn** [comment]
В виджете с завершёнными курсами делаем кнопку "посмотреть результаты". Она ссылается на страницу результатов.
