### ISSUE TITLE
Сделать отчёты

### ISSUE THREAD

**Issue by Nenuahule** [aikus/sql-exam#132]
В менюхе сделать вкладку отчёты, которая будет вести на список курсов
При выборе курса открывать следующую таблицу:
![image](https://user-images.githubusercontent.com/103943533/203541766-96cd7855-9a66-4cea-b276-8d89a1bcd764.png)

При нажатии кнопки "Подробности" выводить страницу результата конкретного пользователя
![image](https://user-images.githubusercontent.com/103943533/203542153-9d3e1b84-db81-42f3-b303-064a8c60e225.png)

Вкладка должна быть доступна для пользователей с ролью тичер и админ

**Comment by germanovn** [comment]
Сделал апиху, завтра отрисую фронтенд

**Comment by germanovn** [comment]
Готово
