### ISSUE TITLE
Сделать кнопку "Посмотреть БД" на форме заполнения опросника

### ISSUE THREAD

**Issue by Nenuahule** [aikus/sql-exam#18]
![image](https://user-images.githubusercontent.com/103943533/164156585-10a62f33-9169-4cdc-afa4-3b6e02610528.png)

**Comment by Nenuahule** [comment]
Кнопка "Посмотреть БД" раскрывает таблицу.
Первая строка таблицы - это названия таблиц БД, которые являются кнопками.
Ниже выводятся атрибуты с данными, где лимит 10

**Comment by germanovn** [comment]
Оценка 4 ч
Выведу атрибуты без данных
