### ISSUE TITLE
Поменять текст на форме с результатами курса

### ISSUE THREAD

**Issue by Nenuahule** [aikus/sql-exam#205]
Поменять текст с "Здесь пока нет данных" на "В этом курсе не было практики или тестов"
Добавить кнопку "Вернуться в личный кабинет", по нажатию которой будет возврат на главный экран

![image](https://github.com/aikus/sql-exam/assets/103943533/7ebd6734-d350-4d40-9a0f-4e9ca08f8983)

**Comment by Nenuahule** [comment]
Ну и до кучи поменять текст 

![image](https://github.com/aikus/sql-exam/assets/103943533/c821fd31-62db-4bb6-b2cd-e880d177d09c)

**Comment by germanovn** [comment]
Я бы предложил формулировку "В этом курсе не было проверяемых ответов"
