### ISSUE TITLE
Убрать для студентов возможность добавлять вопросы и создавать опросы

### ISSUE THREAD

**Issue by Nenuahule** [aikus/sql-exam#21]
![image](https://user-images.githubusercontent.com/103943533/164157680-379ec746-f7e2-4c2d-9691-53f12b2b65df.png)
![image](https://user-images.githubusercontent.com/103943533/164157708-1fcd91eb-0826-4ce9-8cd8-d2aac477ca05.png)

**Comment by germanovn** [comment]
Оценка 1 ч
Если не успею получу люлей
