### ISSUE TITLE
Сделать кнопку "Посмотреть оставшееся время"

### ISSUE THREAD

**Issue by Nenuahule** [aikus/sql-exam#23]
![image](https://user-images.githubusercontent.com/103943533/164158970-f90b83cc-1b64-4fba-9f3b-94c1a739ad2d.png)
![image](https://user-images.githubusercontent.com/103943533/164159174-69c32f22-9e83-45f2-8198-e7b7efbb270b.png)

Сделать в форме прохождения опроса кнопку "Посмотреть оставшееся время". По нажатию показать вместо кнопки таймер с количеством оставшегося времени на 5 секунд, затем скрыть и вернуть кнопку.

**Comment by germanovn** [comment]
4ч

**Comment by aikus** [comment]
Сделяль
