### ISSUE TITLE
Страница личного кабинета

### ISSUE THREAD

**Issue by Slumzur** [aikus/sql-exam#84]
Сверстать страницу личного кабинета

**Comment by Nenuahule** [comment]
Добавить вкладку "Личный кабинет"

![image](https://user-images.githubusercontent.com/103943533/197819812-9a33e2d8-237f-4e4d-aec8-74970b030d82.png)

**Comment by Nenuahule** [comment]
Выводить блоки курсов как в мокапах. 
В блоке с завершёнными выводить кол-во баллов

![image](https://user-images.githubusercontent.com/103943533/197820161-cf30026f-3bf2-431e-b2cc-75711913cca2.png)
